#### Combining Data ####

## Combining Columns ####

" Joins "
" In practise, often different departments
  handle / store different information.
  We wish to combine all these information
  into one single dataset.

  Joins help us achieve this objective.
"

" Concepts to be known:
  Primary Key
  Foriegn Key
"

" Types of Joins:
  1.) Left Join
  2.) Right Join
  3.) Inner Join 
"

" Problem "
"
You work for the DS team of 
TATA AIG General Insurance.

Investigate the nos. of Policies where the
companies have made a loss standing today.
"


" Exercise "
" Final Marks are to be Submitted to the
  Exam department for MSc ASA Sem - I 

  All faculties have given you the marks for their
  respective papers.
  Combine all the information in one excel sheet
  before sending it further.
  
  NOTE:
  It has been conveyed that all students were
  present for PMDA exam.
  
"




#### Summarizing Data Using DPLYR ####

" At times, we may want to find
  information at an overall level
  by creating Summaries.

  Similar to Pivot tables in Excel 

 For. example:
      Total Business written by a General Ins
      Co. across all states in India

      Total Profit generated by each customer
      on Amazon "



' Pipe Operator (%>%) '
# Syntax:
# Data %>% group_by() %>% summarize()

" Understanding:
  group_by() takes variables against which
  the grouping of data is to be done 
  (Specifying rows in Excel)

  summarise() take variables and
  function over which aggregation 
  is to be made "

" Eg.
  Import the dataset 'Sales' and understand
  the Data.

  Find out the Total Profit generated by
  each unique Customer. "


library(dplyr)

Sales = read.csv("C:/Users/tanis/Desktop/Unit 2-Data/Sales.csv")

Profit_Agg = Sales %>% group_by(Customer.ID) %>% 
  summarise(Total_Profit = sum(Profit))

